### ISSUE TITLE
Help -> About buttons doesn't work

### ISSUE THREAD

**Issue by sharov-am** [lacmus-foundation/lacmus-app#106]
On my machine, win 8.1, buttons doesn't react on click, nothing happens.

**Comment by gosha20777** [comment]
Omg. It is very interesting. I'll try to install Windows8 on my Virtual box and check it.

What do you mean under help -> about? Do you mean the full about window? can you cast e.g. gif animation and pin it here?)

**Comment by gosha20777** [comment]
can i close it?
#107

**Comment by sharov-am** [comment]
Sure
