### ISSUE TITLE
Items in the context menu are not available during image processing

### ISSUE THREAD

**Issue by gserrg** [lacmus-foundation/lacmus-app#118]
I see no reason to do this, so these points are not handler specific.

Не вижу причин так делать, т.к. эти пункты не завязаны на обработчик.

**Comment by gosha20777** [comment]
During image processing many opportunities with main thread is locked. So these items is unavailable. Okay I will try to refactoring work with threads to make more functional available during images processing. In addition I will add ability to cancel long operations. I think it will be it 0.5.X or 0.6.X version.

Во время обработки изображения многие возможности в основным потоком становится заблокироваными. Поэтому, многое функции становится недоступны. В грядущих обновлениях, я попробую провести рефакторинг работы с потоками, чтобы сделать доступными больше функций при обработке изображений. Дополнительно добавлю возможность отмены длительных операций. Думаю, это будет в версия 0.5.X или 0.6.X.

**Comment by gosha20777** [comment]
#105
