### ISSUE TITLE
При сохранении результата обработки в виде кропов добавлять поля к изображениям

### ISSUE THREAD

**Issue by gserrg** [lacmus-foundation/lacmus-app#119]
Пикселей по 100 с каждой стороны сделает всё кропы юзабельными

**Comment by gosha20777** [comment]
Duplicate of #43

**Comment by gserrg** [comment]
@gosha20777 нет, не дубликат #43 создавался когда на выходе не было нарезки изображение (просто сохранялись фотографии, на которых произошел детект). Если память не изменяет сейчас все пожелания из #43 в том или ином виде уже учтены и его можно закрыть

А тут запрос к более свежей версии, попросил добавить поля именно к изображениям, создаваемым как кропы зон детекта.
