### ISSUE TITLE
new ML Sore UI

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-app#121]
Rename `ML Model Manager` to `Model Store` and make new UI

I think ti can be s store with 2 tabs
- Explore
- Installed

and with lists e.g. Ubuntu Store
![Screenshot from 2021-02-17 20-39-30](https://user-images.githubusercontent.com/25365364/108244806-a8ef8280-7160-11eb-9357-54c0694a6f2a.png)

**Comment by gosha20777** [comment]
![photo_2021-02-17_20-54-08](https://user-images.githubusercontent.com/25365364/108246367-67f86d80-7162-11eb-9a38-b2eff78c5ae6.jpg)

...and `installed` tub should be like [`ml settings`](https://github.com/lacmus-foundation/lacmus-app/issues/120) tab

**Comment by avbelkin** [comment]
https://www.figma.com/file/o6FIUV2oYSlZLzRcR3Vesi/LACMUS?node-id=0%3A1

**Comment by gosha20777** [comment]
41536639eecccb077875f973b1a4ccfd8d9a27b2
![Screenshot from 2022-02-13 00-20-24](https://user-images.githubusercontent.com/25365364/153728902-56b9201e-56f8-4c41-bf6f-9c51f765d2de.png)
