### ISSUE TITLE
Add Russian to the interface.

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-app#15]
We need support for several languages ​​in the application interface: Russian and English.

**Comment by worldbeater** [comment]
We could either write a custom [markup extension](https://avaloniaui.net/docs/binding/bindings) which could have a syntax like this:
```xml
<TextBlock Text="{Localize SomeString}" />
```
But, with this approach we lose intellisense over our resource keys. 

Another way is to use `.resx` files and a resource generator based on `CultureInfo`, which produces strongly typed localized static fields. I'd prefer the latter approach over the former. But, this approach enforces a user to restart the app to have language changes applied. 

Yet another way is to add a `LocalizationContext` class to the view models, and bind to that context as to one of the view model properties. This will allow us to have localized strings updated without closing and reopening the app. Implementing this pattern with ReactiveUI is a rather simple task, although will be more verbose compared to the first two options. So, the question is,

Should the application provide the ability to change the language used in UI without restart required?

**Comment by gosha20777** [comment]
Hmm... 
This is an interesting question. I think not. Nothing prevents showing a warning asking to restart the application when changing the language to the user.

Thanks for the suggestion. I think that this option is suitable for us. In addition, it will not be difficult to implement.
Thanks for the useful information!

**Comment by gosha20777** [comment]
add some localization at 40be9ec534c2b0bb4d975daf079cd2fff797ddca by @Kubalack <razakov.rus@yandex.ru>

**Comment by gosha20777** [comment]
done at add 536cfcf
