### ISSUE TITLE
Remove user authorization! 

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-app#17]
Open source should be free! To hell with passwords and restrictions.

*P.s. Authorization was introduced first at the request of Lisa Alert. However, then after much persuasion and explanation, we convinced them that there was no point in authorization.*

**Comment by gserrg** [comment]
Если запускается на локальной машине конечно не нужно, но если обработка на ваших серверах, там-то нужно ограничить доступ.

**Comment by gosha20777** [comment]
В текущем виде аутентификациия не нужна

А в будущем думаю в настройках при выборе типа работы через уделенный сервер отображать поле - ввезти api ключ и производить аутентификацию по токену

**Comment by gserrg** [comment]
Ох не думаю, что обычному пользователю будет удобно в одном месте регистрироваться, получать там ключ и вводить его в другом месте. Лучше оставить имеющееся окно регистрации, но данные передавать на реальный сервер.

**Comment by gosha20777** [comment]
- user authorization was cut in the commit b66e368b7fc495bd860b21118fb1ba93a85e35ce
- if necessary, we will add it.
- in addition, it will be possible to associate user authorization and user account with an account in the docker hub.
