### ISSUE TITLE
Beautiful photo metadata

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-app#18]
Currently, metadata is only displayed using the messagebox window. However, it is necessary:
- make a friendlier interface
- put this code in a separate vm
- add the function "copy coordinates to the clipboard" so that later they can be pasted into Google maps for example
- add a tabular view for this data

**Comment by gserrg** [comment]
Ешё не помешают ссылки вида:

- https://www.google.ru/maps/@{lat},{lng},15z
- https://yandex.ru/maps/?ll={lng}%2C{lat}&z=15

**Comment by gosha20777** [comment]
added in 2638d9f7af1f8bc4eded71d72709c9c821071851
![Снимок экрана от 2020-04-01 19-36-56](https://user-images.githubusercontent.com/25365364/78163326-ecf66d80-7450-11ea-862f-383577220512.png)
