### ISSUE TITLE
Add loger 

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-app#20]
Add the logger with file and console handlers instad of `Console.Writeline()` method.

**Comment by worldbeater** [comment]
Probably we should use [Serilog](https://github.com/serilog/serilog) due to the fact, that Avalonia supports it [out of the box](http://avaloniaui.net/docs/logging).

**Comment by gosha20777** [comment]
@worldbeater thanks a lot for awesome suggestion!
- I added logger at cca1f27e781b85bb997e33992fcc8d8bc4fbf9cb

- add ml ml configuration file to make ability to change ml models from repositories.
the structure is
```json
{
   "Url": "ml server url",
   "Image": 
   {
      "Tag": "ml model type",
      "Name": "ml model repo"
   },
  "Accaunt":
   {
      "Email": "e-mail",
      "Username": "user",
      "Password": "password"
   },
   "Type": 0,
   "ApiVersion": 1,
   "ModelVersion": 3
}
```

what do you think about such initialization and usage?
https://github.com/lacmus-foundation/lacmus-app/blob/dev_refactoring/Program.cs#L21
