### ISSUE TITLE
Upgrade TargetFrameworks to netcoreapp3.1

### ISSUE THREAD

**Issue by rstm-sf** [lacmus-foundation/lacmus-app#22]
Hello!

We can upgrade TargetFrameworks to netcoreapp3.1?

In addition, it would be better if everything except a few files (.gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, RescuerLaApp.sln, mk-release.sh, nuget.config) was in the src / source folder for clarity :)

**Comment by gosha20777** [comment]
Regarding the transfer of project files to the src folder. I don’t know how important this is. In fact, if you look at the projects from here (https://github.com/AvaloniaCommunity/awesome-avalonia), there are different options for how to store the project.

However, such a placement would be really convenient. Thanks for the suggestion. I think that I (or someone) will do it.

**Comment by gosha20777** [comment]
2e958d06e8f9663ebbbde9a9f881076e8028c652

**Comment by rstm-sf** [comment]
Thanks! Can we close or do you want to do something else?

**Comment by gosha20777** [comment]
One more point. We want move files to src/ and update readme (build instructions). Contrubutions are welcome. Just create the branch from `dev` with `dev_<short_descriplion>_#<issue_number>`.
