### ISSUE TITLE
The name of files in leаt panel is very small

### ISSUE THREAD

**Issue by gserrg** [lacmus-foundation/lacmus-app#47]
For example `DJI {~} 6.JPG` omitted a significant part of the name. There is more than enough space for a full name (less than half of the available space is used).

And in general, the available space is not used optimally: images can be much larger, the active element can be highlighted with the color of the entire background, and not take away 8px border.

**Comment by gosha20777** [comment]
@gserrg add a new feature in bea3b2a654c29248275a05f91e32c0aa08a446bc
so now the space usage is more rational. But the design is terrible :-1: 

Now small indexers are drawn over the thumbnail of the image.

1. Is there an object in the picture or not.
2. Whether the picture is favorite or not.
3. Whether the user viewed the picture or not.

![Снимок экрана от 2020-03-26 01-33-17](https://user-images.githubusercontent.com/25365364/77594490-b62bcf00-6f07-11ea-9cf5-cdb4cac36fb2.png)

**Comment by gosha20777** [comment]
I add these functional at 6d713dfc2b83aec6e22c3a9e3a6eccefb575e6d4.

So if the lengh of the name is mare than 15, i will try to take only digit symbols or cut the name and replace some of this part to `{~}`. In my opinion 15 characters are enough to determine the name of the picture. Otherwise, you can always focus your mouse cursor the caption and see the full path to the file in the prompt.

```csharp
        public static string GetCaption(this Annotation annotation)
        {
            var name = Path.GetFileNameWithoutExtension(annotation.Filename);
            if (name.Length <= 15)
                return name;
            
            var digitName = Regex.Replace(name, @"[^\d]", "");
            if (!string.IsNullOrWhiteSpace(digitName))
                name = digitName;
                
            if (name.Length > 15)
            {
                name = name.Substring(0, 3) + "{~}" + name.Substring(name.Length - 10);
            }
            return name;
        }
```
