### ISSUE TITLE
Use raliable pathes instad of absolute pathes in output XML

### ISSUE THREAD

**Issue by gserrg** [lacmus-foundation/lacmus-app#50]

**Comment by gosha20777** [comment]
@gserrg Why not use absolute paths? I specifically made them absolute to make it more convenient.

Почему не использовать абсолютные пути? Я специально делал их обсолютными для большего удобства.

**Comment by gserrg** [comment]
@gosha20777 переносишь файлы на другую машину и всё, эти пути не корректные. У тебя при сохранении картинки всегда лежат рядом с xml. Если бы ты выгружал только XML, то можно было считать оправданным, но и тогда для лучшей целостности не нужно спрашивать куда экспортировать, а делать папку для xml внутри обрабатываемой и оставлять пути относительными (`../dj1000.jpg`).

**Comment by gosha20777** [comment]
@gserrg я понял. Нет создавать папок я не буду. Иногда на это нужны доп. права. Буду делать относительные пути. 

И вообще надо добавить пункты 
Сохранить фото и xml
Сохранить xml
Сохранить только фото с рамками 
Сохранить вырезанные объекты. 

Черт много вариантов. Нужно сохранить как и диалоговое окно чтоб пользователь сам выбирал нужные галки. А при сохранить - сохранить фото и xml. Окей. Этот функционал добавлю вместе с #43

**Comment by gosha20777** [comment]
![photo_2020-04-03_01-11-30](https://user-images.githubusercontent.com/25365364/78304773-24941100-7548-11ea-8004-0704855edd60.jpg)

draw a disign

**Comment by gosha20777** [comment]
add save as window at 86c33bb02ceb1810fa14db132689a2ce1be5d1e7
![Снимок экрана от 2020-04-05 22-20-32](https://user-images.githubusercontent.com/25365364/78507909-bb044480-778b-11ea-97a8-a2cdf9943455.png)

**Comment by gosha20777** [comment]
it remains to redo the loading and saving of images so that the path to the files is relative.
and fix `input path` to `output` :smiley:

**Comment by gosha20777** [comment]
Unfortunately, the process of drawing a rectangle on a photograph takes quite a lot of time, as does the process of cutting out an area from a photograph. since for this you need to transcode the image from one format to another. I don’t know yet how to make this process faster.

**UPD:**
Solve the problem by parallelize the task functions at bc9fb97f74f918f49d62f6d37641e1ccbca2226a

**Comment by gserrg** [comment]
bbox crops: изображения должны быть чуть больше самих bbox, например увеличивать до 500х500 это позволит анализировать изображения с учётом окружающего мира, но без необходимости масштабировать.
Подобный диалог нужно на последний шаг визарда прикрутить.

**Comment by gosha20777** [comment]
fixed 4206fb6b9635c37e8828c545848653a67809fa2f
