### ISSUE TITLE
Add function "Report image processing result"

### ISSUE THREAD

**Issue by gserrg** [lacmus-foundation/lacmus-app#66]
It is necessary to automate the collection of false positives and people not found in the lacmus photo storage.

It will be a plus to give the opportunity to mark up directly in the application.

---
Нужно автоматизировать сбор ложных срабатываний и не найденных людей в хранилище лакмуса.

Будет плюсом дать возможность размечать прямо в приложении.

**Comment by gosha20777** [comment]
Yes, I also thought about that. When we deal with the servers and the backend, we will begin to implement this functionality.

**Comment by gosha20777** [comment]
Okay. This function was removed

**Comment by gosha20777** [comment]
![Screenshot from 2020-08-17 15-28-43](https://user-images.githubusercontent.com/25365364/90396244-8b047080-e09e-11ea-9646-1fc38f7504d4.png)

add at 65d47aabbd013c5f5f74efff02af8fa4e4daafe6
