### ISSUE TITLE
Не открывается первое фото сразу после загрузки папки

### ISSUE THREAD

**Issue by nvsit** [lacmus-foundation/lacmus-app#69]
Действия:
- запустить приложение
- нажать кнопку Open, выбрать папку с фотографиями; в левой части отображаются фото
- нажать на первую фотографию в левой части (одинарный или двойной клик)

Выбранная фотография не отображается в правой части

Примечание:
* Проблема существует, только если выбирать в самом начале первое фото
* Если после выбора первого фото выбрать друге фото, то другое фото отобразится как нужно. После этого действия выбор первого фото приводит к нормальному поведению (фото отображается)

**Comment by nvsit** [comment]
Версия приложения: 0.3.3-preview2 alpha

**Comment by gserrg** [comment]
Решено в рамках #51
