### ISSUE TITLE
Predict This function is not worked 

### ISSUE THREAD

**Issue by nvsit** [lacmus-foundation/lacmus-app#70]
- run the application
- upload a photo
- select photo
- select menu Image -> Predict This
Search for an object in the photo does not occur. In the log - no mention of the beginning of the prediction.

**Comment by gosha20777** [comment]
Thanks for the comment. In fact, this function does nothing. The fact is that it remains from the previous version and is now being redone. Also, I have doubts about whether the user needs such a function at all?

**Comment by gosha20777** [comment]
Okay. This function was removed at #74
