### ISSUE TITLE
Невозможно посмотреть обработанные фотографии

### ISSUE THREAD

**Issue by nvsit** [lacmus-foundation/lacmus-app#71]
Действия:
* Запустить Wizard, пройти все шаги. На одном из шагов выбрать место для сохранения фото
* Закрыть приложение и запустить заново
* Выбрать меню File - Import all from XML..., выбрать папку, в которых ранее сохранились фото

Фото загрузились, но отметки о найденных людях на фото не отображаются.
Включение/выключение кнопки Border ничего не изменяет

**Comment by nvsit** [comment]
Version 0.3.3-preview2 alpha

**Comment by gserrg** [comment]
Решено в #52
